version: '3'
services:
  user-api:
    build:
      context: .
    ports:
      - "8081:8080"
  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user
      - TZ=Asia/Tokyo
  redis:
    image: "redis:alpine"
    command: redis-server

volumes:
  db:
